language: cpp
sudo: required
dist: trusty
notifications:
  irc: "chat.freenode.net#zoneminder-dev"
branches:
  except:
    - modern
cache: ccache
addons:
  sauce_connect:
    username: "zoneminder"
    access_key: "046ec7c1-c598-4e7e-949a-f86e725d1722"
env:
    matrix:
    - OS=el DIST=6
    - OS=el DIST=7
    - OS=fedora DIST=24
    - OS=fedora DIST=25
    - OS=ubuntu DIST=trusty
    - OS=ubuntu DIST=xenial
compiler:
    - gcc
services:
    - mysql
    - docker
addons:
  apt:
    sources:
    # We need this ppa for libsys-meminfo-perl 
    - sourceline: 'ppa:iconnor/zoneminder'
    - key_url: 'http://keyserver.ubuntu.com:11371/pks/lookup?op=get&search=0x4D0BF748776FFB04'
    packages:
    - gdebi
    - yum-utils
    - patch
    - git
    - curl
script:
  - utils/packpack/startpackpack.sh
    # TO-DO move the following to an external script file
  - if [ ${OS} == "ubuntu" ] && [ ${DIST} == "trusty" ]; then 
    set -ev;
    sudo gdebi --non-interactive build/zoneminder_*amd64.deb;
    sudo chmod 644 /etc/zm/zm.conf; 
    mysql -uzmuser -pzmpass zm < db/test.monitor.sql; 
    sudo /usr/bin/zmpkg.pl start; 
    sudo /usr/bin/zmfilter.pl -f purgewhenfull;
    fi
deploy:
  # Deploy packages to PackageCloud
  provider: packagecloud
  username: ${PACKAGECLOUD_USER}
  repository: ${PACKAGECLOUD_REPO}
  token: ${PACKAGECLOUD_TOKEN}
  dist: ${OS}/${DIST}
  package_glob: build/*.{deb,rpm}
  skip_cleanup: true
  on:
    branch: master
    condition: -n "${OS}" && -n "${DIST}" && -n "${PACKAGECLOUD_TOKEN}"

