name: Create packages

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  package:
    strategy:
      matrix:
        os_dist:
          - os: debian
            dist: buster
          - os: debian
            dist: bullseye
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Run packpack
        env:
          SMPFLAGS: -j4
          OS: ${{ matrix.os_dist.os }}
          DIST: ${{ matrix.os_dist.dist }}
          DOCKER_REPO: iconzm/packpack
        run: utils/packpack/startpackpack.sh

      - name: Publish
        uses: nogsantos/scp-deploy@master
        with:
          src: ./build/*.{deb,dsc,tar.xz,buildinfo,changes}
          host: ${{ secrets.ZMREPO_HOST }}
          remote: debian/master/mini-dinstall/incoming/
          port: ${{ secrets.ZMREPO_SSH_PORT }}
          user: ${{ secrets.ZMREPO_SSH_USER }}
          key: ${{ secrets.ZMREPO_SSH_KEY }}
